config/routes.rb
Rails.application.routes.draw do




  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :customer do
    get '/customers/sign_out' => 'public/sessions#destroy' #ログアウトできなくなったので追加
  end
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_scope :admin do
    get '/admin/sign_out' => 'admin/sessions#destroy' #ログアウトできなくなったので追加
  end


  root :to =>"public/homes#top"
  get "/about" => "public/homes#about"
  get "/admin" => "admin/homes#top"

  scope module: :public do
    resources :items
    get "search" => "searches#search"
    get '/genre/searches' => 'searches#genre_searches'
    get '/customers/unsubscribe', to: 'customers#unsubscribe', as: 'customer_unsubscribe'
    patch '/customers/withdraw', to: 'customers#withdraw', as: 'customer_withdraw'
    get '/customers/withdraw' => 'customers#withdraw'
    delete '/cart_items/destroy_all', to: 'cart_items#destroy_all', as: :cart_items_destroy_all
    resources :customers
    resources :cart_items
    resources :orders, only: [:new, :index, :show, :create] do
      get 'confirm', on: :collection
      get 'thanks', on: :collection
    end
    post '/orders/confirm', to: 'orders#confirm', as: 'other_confirm_orders'
    post '/orders/thanks', to: 'orders#thanks', as: 'order_thanks'
    resources :addresses, param: :id, only: [:index, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :items
    resources :genres
    resources :customers
    resources :orders, only: [:show, :update]
    patch '/orders/:order_id/order_details/:id', to: 'order_details#update', as: 'order_details'
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # 現在の顧客の注文一覧を返すメソッド
  def orders
    Order.where(customer_id: self.id)
  end
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :family_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :telephone_number, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

end

app/controllers/admin/customers_controller.rb
# module Admin　←モデル名Adminが存在し、名前がブッキングしてエラーになるのでコメントアウトしてます
  class Admin::CustomersController < ApplicationController
    before_action :authenticate_admin!

    def index
      @word = params[:word]
      
      if @word.present?
        @title = "「#{@word}」の検索結果"
        @customers = Customer.where("CONCAT(family_name, first_name) LIKE ?", "%#{@word}%").page(params[:page]).per(10)
      else
        @title = "会員一覧"
        @customers = Customer.page(params[:page]).per(10)
      end
    end

    def show
      @customer = Customer.find(params[:id])
    end

    def edit
      @customer = Customer.find(params[:id])
    end

    def update
      customer = Customer.find(params[:id])
      customer.update(customer_params)
      flash[:notice] = "編集が完了しました。"
      redirect_to admin_customer_path(customer.id)
    end

    private

    def customer_params
      params.require(:customer).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :telephone_number, :postal_code, :address, :email, :is_deleted)
    end
  end
# end

app/views/admin/customers/edit.html.erb
<div class="container">
   <h4 class="p-3 d-inline-block" style="background-color: #CCCCCC; margin-bottom: 40px;">
     <%= @customer.family_name + @customer.first_name %>さんの会員情報編集</h2>
   </h4>
</div>

<%= form_with model: @customer, url: admin_customer_path do |f| %>
 <div class="container">
  <div class="row">
    <div style="display: flex; margin-bottom: 20px;">
      <span style="margin-left: 23px;">
        会員ID
      </span>
      <span style="margin-left: 135px;"> 
        <%= @customer.id %>
      </span>
    </div>
  </div>
  <div class="row">
    <div style="display: flex; margin-bottom: 20px;">
      <span style="margin-left: 23px;">
        氏名
      </span>
      <span style="margin-left: 150px;"> 
        <%= f.text_field :family_name, style: "margin-right: 40px;" %><%= f.text_field :first_name %>
      </span>
    </div>
  </div>
  <div class="row">
    <div style="display: flex; margin-bottom: 20px;">
      <span style="margin-left: 23px;">
        フリガナ
      </span>
      <span style="margin-left: 118px;"> 
        <%= f.text_field :family_name_kana, style: "margin-right: 40px;" %><%= f.text_field :first_name_kana %>
      </span>
    </div>
  </div>  
  <div class="row">
    <div style="display: flex; margin-bottom: 20px;">
      <span style="margin-left: 23px;">
        郵便番号
      </span>
      <span style="margin-left: 118px;"> 
        <%= f.text_field :postal_code %>
      </span>
    </div>
  </div>
  <div class="row">
    <div style="display: flex; margin-bottom: 20px;">
      <span style="margin-left: 23px;">
        住所
      </span>
      <span style="margin-left: 150px;"> 
        <%= f.text_field :address, style: "width: 600px;"%>
      </span>
    </div>
  </div>
  <div class="row">
    <div style="display: flex; margin-bottom: 20px;">
      <span style="margin-left: 23px;">
       電話番号
      </span>
      <span style="margin-left: 120px;"> 
      <%= f.text_field :telephone_number %>
      </span>
    </div>
  </div>
  <div class="row">
    <div style="display: flex; margin-bottom: 20px;">
      <span style="margin-left: 23px;">
        メールアドレス
      </span>
      <span style="margin-left: 75px;">   
        <%= f.email_field :email %>
      </span>
    </div>
  </div> 
  <div class="row">
    <div style="display: flex; margin-bottom: 20px;">
      <span style="margin-left: 23px;">
        会員ステータス
      </span>
      <span style="margin-left: 75px;"> 
        <span style= "margin-right: 40px">
          <%= f.radio_button :is_deleted, :true %>
          <%= f.label :is_deleted, "有効", value: :true, class: "text-success" %>
        </span>
        <span> 
          <%= f.radio_button :is_deleted, :false %>
          <%= f.label :is_deleted, "退会", value: :false, class: "text-danger" %>
        </span>
        
  <div class="row">
    <div style="display: flex; margin-top: 20px;">
      <span style="margin-left: 10px;">  
        <%= f.submit "変更を保存", class: "btn btn-success btn-lg", style: "width: 190px;" %>
      </span>
    </div>
  </div> 
<% end %>

app/views/admin/customers/index.html.erb
<div class="container">
  <h4 class="p-3 d-inline-block" style="background-color: #CCCCCC; margin-bottom: 40px;">
   <%= @title %>
  </h4>
  <div>
    <%= form_with url: admin_customers_path, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.submit "検索" %>
    <% end %>
  </div>
</div>

 <div class="container">
  <div class="row">
    <div class="col-md-12">
      <table class="table">
        <thead>
          <tr>
            <th class="text-left">会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
       
      <tbody>
        <% @customers.each do |customer| %>
      
          <tr>
            <td><%= customer.id %></td>
            <td  style="text-decoration: underline; color: black;">
              <%= link_to customer.family_name + customer.first_name, admin_customer_path(customer.id), style: "color: #000000;" %>
            </td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_deleted == true %>
                <p class = "text-success">有効</p>
              <% else %>
                <p class = "text-danger">退会</p>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </div>
  </div>
 </div>
  <%= paginate @customers %>
</table>

app/views/admin/customers/show.html.erb
<div class="container">
   <h4 class="p-3 d-inline-block" style="background-color: #CCCCCC; margin-bottom: 40px;">
    <%= @customer.family_name + @customer.first_name %>さんの会員詳細
   </h4>
</div>

<div class="container">
  <div class="row">
    <div style="display: flex; margin-bottom: 20px;">
      <span style="margin-left: 23px;">
        会員ID
      </span>
      <span style="margin-left: 135px;"> 
        <%= @customer.id %>
      </span>
    </div>
  </div>
  <div class="row">
    <div style="display: flex; margin-bottom: 20px;">
      <span style="margin-left: 23px;">
        氏名
      </span>
      <span style="margin-left: 150px;">
        <%= @customer.family_name + @customer.first_name %>
      </span> 
    </div>
  </div>
  <div class="row">
    <div style="display: flex; margin-bottom: 20px;">
      <span style="margin-left: 23px;">
        フリガナ
      </span>
      <span style="margin-left: 117px;">
        <%= @customer.family_name_kana + @customer.first_name_kana %>
      </span> 
    </div>
  </div>
  <div class="row">
    <div style="display: flex; margin-bottom: 20px;">
      <span style="margin-left: 23px;">
        郵便番号
      </span>
      <span style="margin-left: 120px;">
        <%= @customer.postal_code %>
      </span>
    </div>
  </div>
  <div class="row">
    <div style="display: flex; margin-bottom: 20px;">
      <span style="margin-left: 23px;">
        住所
      </span>
      <span style="margin-left: 150px;">
        <%= @customer.address %>
      </span>
    </div>
  </div>
  <div class="row">
    <div style="display: flex; margin-bottom: 20px;">
      <span style="margin-left: 23px;">
        電話番号
      </span>
      <span style="margin-left: 120px;">
        <%= @customer.telephone_number %>
      </span>
    </div>
  </div>  
   <div class="row">
    <div style="display: flex; margin-bottom: 20px;">
      <span style="margin-left: 23px;">      
        メールアドレス
      </span>
      <span style="margin-left: 74px;">  
        <%= @customer.email %>
      </span>
    </div>
  </div>    
  <div class="row">
    <div style="display: flex; margin-bottom: 20px;">
      <span style="margin-left: 23px;">      
        会員ステータス
      </span>
      <span style="margin-left: 74px;">      
            <% if @customer.is_deleted == true %>
                <p class = "text-success">有効</p>
            <% else %>
                <p class = "text-danger">退会</p>
            <% end %>
      </span>
    </div>
  </div>
  <div class="row">
    <div style="display: flex; margin-bottom: 20px;">
      <span style="margin-left: 210px;">  
   <%= link_to "編集する", edit_admin_customer_path, class: "btn btn-success btn-lg", style: "margin-right: 30px;" %>
    </span>
      <span style="margin-left: 74px;">   
   <%= link_to "注文履歴一覧を見る", admin_path, class: "btn btn-primary btn-lg" %>
     </span>
    </div>
</div>