config/routes.rb
Rails.application.routes.draw do




  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :customer do
    get '/customers/sign_out' => 'public/sessions#destroy' #ログアウトできなくなったので追加
  end
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_scope :admin do
    get '/admin/sign_out' => 'admin/sessions#destroy' #ログアウトできなくなったので追加
  end


  root :to =>"public/homes#top"
  get "/about" => "public/homes#about"
  get "/admin" => "admin/homes#top"

  scope module: :public do
    resources :items
    get "search" => "searches#search"
    get '/genre/searches' => 'searches#genre_searches'
    get '/customers/unsubscribe', to: 'customers#unsubscribe', as: 'customer_unsubscribe'
    patch '/customers/withdraw', to: 'customers#withdraw', as: 'customer_withdraw'
    get '/customers/withdraw' => 'customers#withdraw'
    delete '/cart_items/destroy_all', to: 'cart_items#destroy_all', as: :cart_items_destroy_all
    resources :customers
    resources :cart_items
    resources :orders, only: [:new, :index, :show, :create] do
      get 'confirm', on: :collection
      get 'thanks', on: :collection
    end
    post '/orders/confirm', to: 'orders#confirm', as: 'other_confirm_orders'
    post '/orders/thanks', to: 'orders#thanks', as: 'order_thanks'
    resources :addresses, param: :id, only: [:index, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :items
    resources :genres
    resources :customers
    resources :orders, only: [:show, :update]
    patch '/orders/:order_id/order_details/:id', to: 'order_details#update', as: 'order_details'
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :cart_items

  validates :postal_code, presence:true
  validates :address, presence:true
  validates :name, presence:true



  #支払い方法
  enum payment_method: {credit_card: 0, transfer: 1}

  #注文ステータス
  enum status: {wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, finish_prepare: 4}

  def self.order_statuses_i18n
        order_statuses.keys.map do |status|
          [I18n.t("enums.order.order_status.#{status}"), status]
        end.to_h
  end

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  

end

app/controllers/admin/orders_controller.rb
# module Admin ←モデル名Adminが存在し、名前がブッキングしてエラーになるのでコメントアウトしてます
  class Admin::OrdersController < ApplicationController
    # before_action :authenticate_customer!
    before_action :authenticate_admin!
    def index
    end

    def show
      @order = Order.find(params[:id])
      # @order_details= OrderDetail.where(order_id: @order.id)
      @order_details = @order.order_details

    end

    def update
      order = Order.find(params[:id])
      order.update(status: params[:order][:status])
      order_details = order.order_details

      if params[:order][:status] == "confirm_payment" #前の画面で「入金確認」が選択されたならを定義
        order_details.update(making_status:"waiting_manufacture") #Order_detailの制作ステータスを「製作待ち」に更新する
      end

      flash[:notice] = "注文ステータスを更新しました。"
      redirect_to admin_order_path(order.id)
    end

  end

    private

    def order_params
      params.require(:order).permit(:status)
    end
# end

app/views/admin/orders/_status.html.erb
<%= form_with model: order, url:admin_order_path(order), method: :patch, local: false do |f| %>
  <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"),k]} %>
  <%= f.submit "更新", class: "btn btn-success" %>
<% end %>

app/views/admin/orders/show.html.erb
<h1 class="m-4">注文履歴詳細</h1>

<div class="m-4">

  <div class="d-flex m-2 text-left">
    <div class="w-25 text-left">購入者</div>
    <div class="w-25 text-left"><%= link_to @order.customer.family_name + @order.customer.first_name, admin_customer_path(@order.customer_id) %></div>
  </div>

  <div class="d-flex m-2 text-left">
    <div class="w-25 text-left">注文日</div>
    <div class="w-25 text-left"><%= @order.created_at.strftime("%Y/%m/%d %H:%M") %></div>
  </div>

  <div class="d-flex m-2 text-left">
    <div class="w-25 text-left">配送先</div>
    <div class="w-25 text-left"><%= @order.postal_code%><%="　"%><%= @order.address %><%="　"%><%= @order.name %>様</div>
  </div>

  <div class="d-flex m-2 text-left">
    <div class="w-25 text-left">支払い方法</div>
    <div class="w-25 text-left"><%= I18n.t("enums.order.payment_method.#{@order.payment_method}") %></div>
  </div>

  <div class="d-flex m-2 text-left">
    <div class="w-25 text-left">注文ステータス</div>
    <div class="w-25 text-left">
      <%= form_with model: @order, url:admin_order_path(@order), method: :patch do |f| %>
        <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"),k]} %>
        <%= f.submit "更新", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>

  <table class="table">
  <thead>
    <tr>
      <th>商品名</th>
      <th>単価(税込)</th>
      <th>数量</th>
      <th>小計</th>
      <th>制作ステータス</th>
      <th><br></th>
    </tr>
  </thead>

  <tbody>
    <% @order_details.each do |order_detail| %>
      <tr>
        <td><%= order_detail.item.name %></td>
        <td><%= order_detail.item.with_tax_price.to_s(:delimited) %></td>
        <td><%= order_detail.amount %></td>
        <td><%= (order_detail.amount * order_detail.item.with_tax_price).to_s(:delimited) %></td>
        <td>
          <%= form_with model: order_detail, url: admin_order_details_path(order_id: @order.id, id: order_detail), method: :patch do |f| %>
              <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"),k]} %>
              <%= f.submit '更新',class:"btn btn-success" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

  <div class="col-md-6">
    <table class="table">
      <tr>
        <th>商品合計</th>
        <td><%= (@order.total_payment - 800).to_s(:delimited) %></td>
      </tr>
      <tr>
        <th>送料</th>
        <td>800</td>
      </tr>
      <tr>
        <th>請求金額</th>
        <td><%= @order.total_payment.to_s(:delimited) %></td>
      </tr>
    </table>
  </div>
</div>

app/views/admin/orders/update.js.erb
$(".status").html("<%= j(render "status", order: @order) %>");