config/routes.rb
Rails.application.routes.draw do




  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :customer do
    get '/customers/sign_out' => 'public/sessions#destroy' #ログアウトできなくなったので追加
  end
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_scope :admin do
    get '/admin/sign_out' => 'admin/sessions#destroy' #ログアウトできなくなったので追加
  end


  root :to =>"public/homes#top"
  get "/about" => "public/homes#about"
  get "/admin" => "admin/homes#top"

  scope module: :public do
    resources :items
    get "search" => "searches#search"
    get '/genre/searches' => 'searches#genre_searches'
    get '/customers/unsubscribe', to: 'customers#unsubscribe', as: 'customer_unsubscribe'
    patch '/customers/withdraw', to: 'customers#withdraw', as: 'customer_withdraw'
    get '/customers/withdraw' => 'customers#withdraw'
    delete '/cart_items/destroy_all', to: 'cart_items#destroy_all', as: :cart_items_destroy_all
    resources :customers
    resources :cart_items
    resources :orders, only: [:new, :index, :show, :create] do
      get 'confirm', on: :collection
      get 'thanks', on: :collection
    end
    post '/orders/confirm', to: 'orders#confirm', as: 'other_confirm_orders'
    post '/orders/thanks', to: 'orders#thanks', as: 'order_thanks'
    resources :addresses, param: :id, only: [:index, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :items
    resources :genres
    resources :customers
    resources :orders, only: [:show, :update]
    patch '/orders/:order_id/order_details/:id', to: 'order_details#update', as: 'order_details'
  end

end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-success">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
         <%= image_tag 'cakerogo.webp', size: '150x150' %><br>
          ==ながのCAKE==<i class="fas fa-leaf"></i>
      </a>
      <ul class="navbar-nav">
        <% if customer_signed_in? %>
          <div class="mt-2 mr-5 text-white" style="margin-right: 40px;">
            <h3>
              <i class="fas fa-sign-language"></i>
              ようこそ、<%= current_customer.family_name + current_customer.first_name %>さん!
            </h3>
          </div>
          <li class="nav-item">
            <%= link_to customer_path(current_customer), class: "nav-link text-light"  do %>
               <h5><i class="fab fa-ello"></i>マイページ</h5>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to items_path, class: "nav-link text-light" do %>
              <h5><i class="fas fa-cheese"></i>商品一覧</h5>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to cart_items_path, class: "nav-link text-light" do %>
               <h5><i class="fas fa-shopping-cart"></i>カート </h5>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_customer_session_path, method: :delete, class: "nav-link text-light" do %>
               <h5><i class="fas fa-door-open"></i>ログアウト </h5>
            <% end %>
          </li>
        <% elsif admin_signed_in? %>
          <li class="nav-item">
            <%= link_to admin_items_path, class: "nav-link text-light" do %>
              商品一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_customers_path, class: "nav-link text-light" do %>
              会員一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_path, class: "nav-link text-light" do %>
              注文履歴一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_genres_path, class: "nav-link text-light" do %>
              ジャンル一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-light" do %>
              ログアウト
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to about_path, class: "nav-link text-light" do %>
              About
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to items_path, class: "nav-link text-light" do %>
              商品一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_customer_registration_path, class: "nav-link text-light" do %>
              新規登録
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_customer_session_path, class: "nav-link text-light" do %>
              ログイン
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/ee0d5227ce.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>